### ISSUE TITLE
Internal compiling error! abording

### ISSUE THREAD

**Issue by fredykoci** [google-coral/edgetpu#104]
Hello I have Tensorflow==2.0, edgetpu-compiler=2.1.302470888 and i can not compile my model to coral and I do not know what to do. There is my model summary:

![obrazek](https://user-images.githubusercontent.com/18038918/81183880-fde65180-8faf-11ea-8dfc-69fca281fe5a.png)

**Comment by Namburger** [comment]
@fredykoci 
What's the error message?

**Comment by fredykoci** [comment]
Internal compiling error! abording

**Comment by Namburger** [comment]
Did you perform a post training quantization on the model? Could you attach it here so we can take a look? Thanks

**Comment by fredykoci** [comment]
> Did you perform a post training quantization on the model? Could you attach it here so we can take a look? Thanks

Yes I perform a post training quantization on the model. And there is a model
[kvantizovan.zip](https://github.com/google-coral/edgetpu/files/4588470/kvantizovan.zip)

**Comment by Namburger** [comment]
@fredykoci I opened an internal bug for this issue, will keep you posted on the status

**Comment by fredykoci** [comment]
Thank you, but I need to use my models, so could you send me older deb package with the compiler?

**Comment by Namburger** [comment]
@fredykoci sorry for this issue, compiler binaries are actually [here](https://github.com/google-coral/edgetpu/tree/master/compiler). We don't ship older compiler as apt packages anymore, you can checkout older commits to get the compiler version that you need

**Comment by KarlKulator** [comment]
Hi,
I get the same error message:
```
Edge TPU Compiler version 2.1.302470888

Internal compiler error. Aborting! 
```

The error seems to be related to reshaping and slicing operations.
Here is my model:

[shuffle.zip](https://github.com/google-coral/edgetpu/files/4793661/shuffle.zip)

**Comment by Namburger** [comment]
@KarlKulator not the same issue, since we have guidance to allow sharing model artifacts from our source, I was able to compile it, here is the compiled model and some logs:
[shuffle.tar.gz](https://github.com/google-coral/edgetpu/files/4794347/shuffle.tar.gz)

**Comment by KarlKulator** [comment]
@Namburger thank you very much.

The issue seems to be fixed in version 2.1.315469171 that you used.
The latest official version I know of is 2.1.302470888.

When will the release be of the new compiler version?

**Comment by Namburger** [comment]
@KarlKulator 
Hey, I don't have an exact date for this but since there is a few other issues that we're also seeing with the AutoML workflow, our team is working to release the next version a little earlier than planned. If you have issues like this, feel free to mention this and send the model to coral-support@google.com, I'll compile it for you ASAP.

As for the original issue here, an internal bug has been filed. I suspect it is the dense layer which the compiler haven't supported yet. This is something that will hopefully be supported soon.

**Comment by johannes-do** [comment]
I am constantly running into this issue and often only change the number of filters and it seems to resolve. Regardless of what the issue actually is, I just wish there would be a more detailed error output so we know what we have to adapt. It is really time-consuming and frustrating otherwise :(

Here is an example model that did not work: 
[model_quant.tflite.zip](https://github.com/google-coral/edgetpu/files/5789573/model_quant.tflite.zip)

**Comment by manoj7410** [comment]
Feel free to reopen if this is still an issue.
