### ISSUE TITLE
feeding batch of images to USB Coral for object detection

### ISSUE THREAD

**Issue by PythonImageDeveloper** [google-coral/edgetpu#106]
Hello,
I want to feed Batch of images to detection models using USB Coral, Is it possible to do this problem with USB Coral accelerator? How?

**Comment by Namburger** [comment]
Hi there,
you can do it like this:
```
images_to_process = read_images() # read all your images
for img in images_to_process:
   img = preprocess_image(img) # to make it fit the model's input tensor
   interpreter.set_input_tensor(img) # set image as input tensor
   interpreter.invoke() # run inference
   output = interpreter.get_output_tensor() # get output tensor
   process_output(output) # process your outputs
```

**Comment by PythonImageDeveloper** [comment]
right, one solution can be this way.
Is it possible to do all images of batch at once and in one forward-path.
I want to know, Is it possible to feed tensort with shape : [N, H,W,C] and get output [N, ....] at the same time ?

**Comment by Namburger** [comment]
@PythonImageDeveloper 
So since the tpu's ram is limited, this make batch processing of images infeasible. If you use tools like [netron](https://github.com/lutzroeder/netron) to check our models, you'll that the input tensor shape is `[1,H,W,C]` as you described.
The problem with multi threading is that most OSes won't allow accessing the hardware resources such as USB at the same time, so things will start crashing as soon as you attempt multi-threading.
Unfortunately, since we're dealing with HW those are limitations, a single tpu would not have enough resources to hold more than one model or inputs. The best solution is to expand to multiple tpus.

**Comment by PythonImageDeveloper** [comment]
how much the USB Coral TPUs has ram?

**Comment by Namburger** [comment]
@PythonImageDeveloper Yes, that's correct. You can take advantage of multi-threading when you have multiple USB Accelerators. Take a look at this example for instance:
https://github.com/google-coral/edgetpu/blob/master/examples/two_models_inference.py#L98

**Comment by PythonImageDeveloper** [comment]
Thanks a lot.

**Comment by Namburger** [comment]
@PythonImageDeveloper Definitely note that our python API is basically a wrapper around the c++, so in the back end, it's actually just c++ doing all the work :)
As far as model execution time, the too language should have no difference in performance.
