### ISSUE TITLE
Do you consider open source the edgetpu_compiler code?

### ISSUE THREAD

**Issue by wuhy08** [google-coral/edgetpu#14]
I see they are provided as binary. Do you plan to open source that?

Thank you!

**Comment by Namburger** [comment]
Hi @wuhy08,
unfortunately we have no plans to open source our edgetpu_compiler at the moment.

**Comment by wuhy08** [comment]
Thank you for the info, @Namburger

**Comment by jk78346** [comment]
Is there any brief explanation about what does the edgetpu_compiler do? And what information the compiled .tflite contains? For some customized models that I run, it is still runnable by just using xxx_quant.tflite rather than xxx_quant_edgetpu.tflite. 
If this is valid, why there is some performance difference?

**Comment by bickelj** [comment]
It looks like the last binary release was around Jun 28 2021. Does this mean the compiler is working well enough or has development on it stopped? If the latter, would you reconsider liberating it?
