### ISSUE TITLE
Run example semantic segmentation with live video and Raspberry Pi 4

### ISSUE THREAD

**Issue by FPSychotic** [google-coral/edgetpu#146]
Hi, I'm totally new with ML and Coral TPU, I got run the major part of examples or equivalents of different sites on RPi4 and Raspberry CSI camera (with picamera python library mainly), but I have not idea with the semantic segmentation example, I have no idea what --model I need use or what --input to use the rpi4 camera, I even dont know if can be a video device /dev/video*, a gs pipeline... it is my bigger interest on Coral TPU (and Pose detection), could somebody please address me in get it work.

My target is with a RGB-D camera can get the metrics of the BB and can label 3D pointclouds. get make work the example would be a great start for me.

Thanks by make open source software and share knowledge

**Comment by manoj7410** [comment]
@FPSychotic EdgeTPU compatible Semantic Segmentation models can be downloaded from https://coral.ai/models/.  
EdgeTPU Python examples are given at : https://github.com/google-coral/edgetpu/tree/master/examples
Semantic segmentation example can be found at : https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py

**Comment by Namburger** [comment]
@FPSychotic hey!
Just FYI, since this isn't a bug and we already have an example on segmentation, [stackoverflow](https://stackoverflow.com/questions/tagged/google-coral) would be a better place for this issue, especially since you are trying to integrate a 3rd party library into it.

Anyhow, if you look at our [segmentation example](https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L20), you'll see that it is using the [deeplabv3_mnv2_dm05_pascal_quant_edgetpu.tflite](https://github.com/google-coral/edgetpu/blob/master/test_data/deeplabv3_mnv2_dm05_pascal_quant_edgetpu.tflite) model.
Basically the process, in the big picture, looks like this:

1) [get input image](https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L110) -> 2) [preprocess-image](https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L111) -> 3) [feed output to model](https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L119) -> 4) [get output](https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L124) -> 5) [post process](https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py#L125-L136)

For you, the `get input`, `preprocess`, and `postprocess` are what needed to be change. If you want to use opencv, it should be something as easy as
```

engine = BasicEngine(path_to_model)

# this object basically represent your camera, source can be any numbers, 
# depending on where your picamera is linked to in `/dev/video*`
cap = cv2.VideoCapture(0)
while(True):
    # 1) Capture frame-by-frame
    # ret gives a retrurn code, frame is basically the image you get from your camera
    ret, frame = cap.read()

    # 2) Here you want to preprocess the image to fit size that this model wants
    input_tensor = apply_your_preprocess(frame)
    
    # 3 and 4 ) Feed input to model and get output
    result = engine.run_inference(input_tensor)

    # 5) Apply post process, this could be anything you want to do with the result.
    processed_frame = apply_post_process(result)

    cv2.imshow('frame', processed_frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
```

Closing this for now, feel free to keep conversation alive here if something still doesn't make sense :)
