### ISSUE TITLE
Does edge tpu support chrome os debian terminal?

### ISSUE THREAD

**Issue by fsx950223** [google-coral/edgetpu#15]

**Comment by Namburger** [comment]
@fsx950223 I'll have to relay this to the team for more info, but afaik, the system requirements are listed here:
https://coral.withgoogle.com/docs/accelerator/get-started/#requirements

**Comment by fsx950223** [comment]
> @fsx950223 I'll have to relay this to the team for more info, but afaik, the system requirements are listed here and Chrome OS is not listed:
> https://coral.withgoogle.com/docs/accelerator/get-started/#requirements

I have installed runtime successful but the device seems hasn't been detected.

**Comment by fsx950223** [comment]
It seems that my usb line is broken.

**Comment by Namburger** [comment]
@fsx950223 Hi again, we are not planning to support Chrome OS due to the fact that Debian in Chrome OS is a very restricted LXC container (and it's in beta). I'm not too familiar with how this Debian containers work but your issue is most-likely due to the container not being able to detect the usb devices (even though your actual OS did). This may be a good link to see how to get it connecting:
https://kmyers.me/blog/chromeos/chromeos-75-0-3759-4-brings-proper-usb-support-to-linux-applications-and-breaks-a-few-things-in-the-process/

Hope this helps!

**Comment by fsx950223** [comment]
> @fsx950223 Hi again, we are not planning to support Chrome OS due to the fact that Debian in Chrome OS is a very restricted LXC container (and it's in beta). I'm not too familiar with how this Debian containers work but your issue is most-likely due to the container not being able to detect the usb devices (even though your actual OS did). This may be a good link to see how to get it connecting:
> https://kmyers.me/blog/chromeos/chromeos-75-0-3759-4-brings-proper-usb-support-to-linux-applications-and-breaks-a-few-things-in-the-process/
> 
> Hope this helps!

It worked. Thank you for your help.
