### ISSUE TITLE
[Question] Is it ok to run coral usb accelerator at max clock ?

### ISSUE THREAD

**Issue by KyungWonPark** [google-coral/edgetpu#150]
Hello

I wonder if it's ok to run it at max speed
if I'm not gonna touch it
Let's say, I'm running it 24/7
Would it be okay to do that? Can it burn itself?
I was curious

Thank you

**Comment by Namburger** [comment]
Hi @KyungWonPark !
How long are you planning on keeping it running? I've found some issues with the dev board when running for too long but not the USB Accelerator. In either case, though, if you're planning to run it 24/7 for months, then it is best to use the throttle version

**Comment by KyungWonPark** [comment]
> Hi @KyungWonPark !
> How long are you planning on keeping it running? If you're planning to run it 24/7 for months, then it is best to use the throttle version.

Well actually no more than few hours 
Curious how hot it gets

**Comment by Namburger** [comment]
I guess this is harder to measure since we haven't provides an API for querying the USB device temperature :/ https://github.com/google-coral/edgetpu/issues/102 (we have it for the dev  board and pcie)
But is is safe to say I have not had any issues using it constantly at max speed, I just [wouldn't recommend it](https://coral.ai/docs/accelerator/datasheet/#recommended-operating-conditions).

**Comment by KyungWonPark** [comment]
> I guess this is harder to measure since we haven't provides an API for querying the USB device temperature :/ #102 (we have it for the dev board and pcie)
> But is is safe to say I have not had any issues using the accelerator constantly at max speed for days, I just [wouldn't recommend it](https://coral.ai/docs/accelerator/datasheet/#recommended-operating-conditions).

Thank you for sharing your experience

https://youtu.be/qJMwNHQNOVU
This video shows(around 3:40) temp at max clock is still under 40 degree celcius
