### ISSUE TITLE
Internal compiler error on small tflite model

### ISSUE THREAD

**Issue by JohannSchumann** [google-coral/edgetpu#173]
Hi,
I am trying to convert a TF (1.X) model for tflite (post-training quantization and uint8) and compile for coral devboard.
I get the (very 80ies style) internal compiler error aborting

Below a small fragment where the error occurs. It seems to be linked to the "reshape" operation.
I also tried: only then placeholder and the split/concat: these can be compiled.
NOTE: I have to use tf 2.X, because TF 1.15 does NOT support split :(   (but that's needed for my model)

Here the versions:
* Edge TPU Compiler version 14.1.317412892
* tensorflow: 2.2.0 (within docker)

Thanks!

```
import tensorflow as tf
import numpy as np

def representative_dataset_gen():
	input = np.array(np.random.random_sample([1,16,16,1,3]), dtype=np.float32)
	for _ in range(10):
		yield [input]

tf.compat.v1.disable_eager_execution()
#-------------------------------------------------------------------------
input = tf.compat.v1.placeholder(tf.float32, [1, 16,16,1,3], name= 'input_LR')
LR = tf.compat.v1.reshape(input, [1,16,16,3],name='TMP_OUT')

# doesn't work either: LR = tf.reshape(input, [1,16,16,3],name='TMP_OUT')

# works:
#out_split = tf.split(input,2,axis=1)
#X = tf.concat(out_split, 0)
# -or-
#X = tf.compat.v1.concat([tf.squeeze(x, axis=0) for x in out_split], 0)

input_name = ["input_LR"]
#OK: output_name = ["input_LR"]
#OK: output_name = ["split", "split:1"]
#OK output_name = ["concat"]
output_name = ["TMP_OUT"]


with tf.compat.v1.Session() as sess:
        tf.io.write_graph(tf.compat.v1.get_default_graph(), '.','split.pb', as_text=False)
#	tf.io.write_graph(tf.compat.v1.get_default_graph(), '.','split.pbtxt', as_text=True)

tflite_model_name = "int8_split.tflite"
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("split.pb", input_name, output_name)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
open(tflite_model_name, "wb").write(tflite_model)


```

**Comment by Namburger** [comment]
@JohannSchumann 
Apologies, there are some limitations with the reshape operators with > 4 dimensions this would have been delegated back to CPU instead of crashing.
We've since fixed the issue internally but the fix did not make the cut for the recent release, for reference:
```
Number of operations that will run on Edge TPU: 1
Number of operations that will run on CPU: 2

Operator                       Count      Status

QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
QUANTIZE                       1          Mapped to Edge TPU
RESHAPE                        1          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
```

If you submit the original model I could try compiling it for you

**Comment by JohannSchumann** [comment]
Hi,

thank you for the prompt response and clarification about the source of the
error.
Are there plans to map the reshape of higher-rank tensorPU eventually? rank
4 or 5 would be great
for processing/combining multiple images.

Also:
The edgetpu_compiler seems to have an uninitialized variable problem:
consecutive identical calls can result in different error messages or can
even succeed to compile. E.g.,

$ edgetpu_compiler T1_no_summ_02_quant8.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting!

$ edgetpu_compiler T1_no_summ_02_quant8.tflite
Edge TPU Compiler version 14.1.317412892
terminating with uncaught exception of type std::length_error: vector

Internal compiler error. Aborting!

Thanks
-johann

**Comment by Namburger** [comment]
@JohannSchumann 
Yes, we're planning on expanding the list of supported ops in the compiler at all time, but the edgepu's RAM size and architect is definitely a bit of a challenge when inputs/dimension get's too large.

Regarding `terminating with uncaught exception of type std::length_error: vector`, that seems like a bug, would you be able to attach the model?

**Comment by JohannSchumann** [comment]
Hi,

Thanks for the response!

Re: uncaught exception etc:
* model attached (from VESPCN repo, modified)
* output of several runs without any changes in model:  (ubuntu 16.04)

$ edgetpu_compiler T1_no_summ_02_quant8.tflite
Edge TPU Compiler version 14.1.317412892

Model compiled successfully in 113 ms.

Input model: T1_no_summ_02_quant8.tflite
Input size: 28.19KiB
Output model: T1_no_summ_02_quant8_edgetpu.tflite
Output size: 116.78KiB
On-chip memory used for caching model parameters: 60.00KiB
On-chip memory remaining for caching model parameters: 7.96MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 24
Operation log: T1_no_summ_02_quant8_edgetpu.log

Model successfully compiled but not all operations are supported by the
Edge TPU. A percentage of the model will instead run on the CPU, which is
slower. If possible, consider updating your model to use only operations
supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 6
Number of operations that will run on CPU: 18
See the operation log file for individual operation details.
$ edgetpu_compiler T1_no_summ_02_quant8.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting!
$ edgetpu_compiler T1_no_summ_02_quant8.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting!
$ edgetpu_compiler T1_no_summ_02_quant8.tflite
Edge TPU Compiler version 14.1.317412892
terminating with uncaught exception of type std::length_error: vector

Internal compiler error. Aborting!
$

**Comment by Namburger** [comment]
@JohannSchumann 
Sorry, I mean the tflite model, not the outputs (if that's okay with you)! It would definitely help us debug the issues

**Comment by JohannSchumann** [comment]
@Namburger  Sorry - had attached the model to the email and it seems it didn't make it.
Hope you can read this:

[T1_no_summ_02_quant8.tflite.gz](https://github.com/google-coral/edgetpu/files/4957798/T1_no_summ_02_quant8.tflite.gz)

-johann

**Comment by Namburger** [comment]
@JohannSchumann Thanks for submitting the model, it's fixed internally for us, so this should not occurs after next release!
Appreciate your helps!

**Comment by InCogNiTo124** [comment]
> @JohannSchumann this should not occurs after next release!

When is the next release scheduled?

**Comment by Namburger** [comment]
Sorry, We don't have a date yet, if you are running into this issue, feel free to drip the model here and I can compile it for you!

**Comment by trungnguyensju** [comment]
> Sorry, We don't have a date yet, if you are running into this issue, feel free to drip the model here and I can compile it for you!

Could you please help me to compile this? I've tried many time but kept getting the same error. Thank you!
[tqn_quantized.tflite.zip](https://github.com/google-coral/edgetpu/files/5468755/tqn_quantized.tflite.zip)

**Comment by manoj7410** [comment]
I believe this was fixed with the newer compiler release. Feel free to reopen if this is still an issue.

**Comment by hjonnala** [comment]
Newer version of edgetpu compiler able to compine tqn_quantized.tfile succeesfully!

Evidence log:

Edge TPU Compiler version 15.0.340273435

Model compiled successfully in 4076 ms.

Input model: /content/drive/Shareddrives/OSS Developer Support/Coral DevSupport/Github & SO Analysis/github/edgetpu/173/tqn_quantized.tflite
Input size: 10.72MiB
Output model: tqn_quantized_edgetpu.tflite
Output size: 30.83MiB
On-chip memory used for caching model parameters: 6.99MiB
On-chip memory remaining for caching model parameters: 50.00KiB
Off-chip memory used for streaming uncached model parameters: 22.79MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 182
Operation log: tqn_quantized_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 176
Number of operations that will run on CPU: 6

Operator                       Count      Status

MUL                            40         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Mapped to Edge TPU
DEPTHWISE_CONV_2D              13         Mapped to Edge TPU
CONCATENATION                  1          More than one subgraph is not supported
CONCATENATION                  1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CUSTOM                         1          Operation is working on an unsupported data type
RESHAPE                        8          Mapped to Edge TPU
RESHAPE                        2          Operation is otherwise supported, but not mapped due to some unspecified limitation
ADD                            42         Mapped to Edge TPU
LOGISTIC                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                        71         Mapped to Edge TPU
