### ISSUE TITLE
ERROR run src/cpp/examples/minimal.cc

### ISSUE THREAD

**Issue by laithehoangbka** [google-coral/edgetpu#19]
when run src/cpp/examples/minimal.cc, i get 

```
ERROR: Null custom op data.
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Failed to allocate tensors.
```

How fix it ???

**Comment by Namburger** [comment]
hi @laithehoangbka How did you compile it and did you run this on the board or on your host machine?
Additionally, did any other demo works?

Edit: Since the current Makefile isn't updated to build minimal, you can try this one:
https://gist.github.com/Namburger/31528aee46eaed3a3dae3b7803024264

So just replace the Makefile from the root of this repo with that one, then
```
$ make examples
$ ./out/k8/examples/minimal ./test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite ./test_data/resized_cat.bmp
```

Hope this helps!

**Comment by laithehoangbka** [comment]
Hi @Namburger,
Thank you for the response.
I compile it and run this on your host machine. I will try your suggestion.

**Comment by Namburger** [comment]
@laithehoangbka [Please check this answer](https://github.com/google-coral/edgetpu/issues/54#issuecomment-616149916) if you are still interested in a known working example build
