### ISSUE TITLE
Copying images from mac to Dev board

### ISSUE THREAD

**Issue by mmmoakley** [google-coral/edgetpu#195]
I have been successfully running the demos and now i am trying to copy images from my mac to the dev board using scp and i keep getting 
Permission Denied (Public Key)
scp tv.jpg mendel@xx.xx.xx.xx:/home/mendal/images
tried sudo scp as well

**Comment by Namburger** [comment]
OH, this isn't a permission denied on your host machine, so `sudo` isn't going to works. 
Simply, Mendel OS is rejecting the file because it doesn't know who your host machine is. In order to add your host to a list of authorized devices on the board, do this:

Create a id_rsa key on your mac with:
```
$ ssh-keygen
```
This creates a `~/.ssh/id_rsa.pub` file on your MAC. You can copy that key over to the board and put the content in `~/.ssh/authorized_keys` (you can put multiple keys in this file for different host machines):
```
$ sudo systemctl restart ssh
```
Now you can start scp-ing:
```
$ scp filename mendel@ip-addr:/path/
```

**Comment by mmmoakley** [comment]
I did something like this when i flashed the board

**Comment by Namburger** [comment]
Can you cat your keys and the authorized file to make sure they are matching? If it's not, then you will run into this issue.

Other wise you can also enable password authentication on mendel.
```
sudo nano /etc/ssh/sshd_config
```
change PasswordAuthentication from no to yes and restart ssh service:
```
sudo systemctl restart ssh
```

Then you can ssh and scp using password instead, the default password is mendel

**Comment by mmmoakley** [comment]
thanks it worked now
