### ISSUE TITLE
How to build tflite_runtime whl for edge tpu board

### ISSUE THREAD

**Issue by dpsm** [google-coral/edgetpu#198]
Is it possible to build from source the tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl referenced here https://coral.ai/docs/dev-board/get-started/#12-execute-the-flash-script ?

I would like to modify existing ops and add custom ops and be able to test non the dev board.

**Comment by Namburger** [comment]
@dpsm 
The main thing to watch for is that you'll need to build it from the same tensorflow commit as: https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5 which is what we depends on.
Here are the steps:

1) Check out tensorflow, this commit: https://github.com/google-coral/edgetpu/blob/master/WORKSPACE#L5
2) Apply this patch (because this commit happens to have a small build bug): https://github.com/tensorflow/tensorflow/commit/72cd947f231950d7ecd1406b5a67388fef7133ea
3) Try building it them self following this guide: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by dpsm** [comment]
@Namburger the build instructions from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package build python 3.5 for aarch64. The package above is python 3.7. 
Can you point to the exact command to build the aarch64 python 3.7 whl? Thanks!

**Comment by Namburger** [comment]
Can you try this one (just change target from armf7h to aarch64)? 
```
tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64
```
It may requires you to install different dependencies in order to produce the correct package. 
Proprably better to build with the docker container to make sure there isn't any mismatch in glibc between your host and the dev board, I think something like this should do it:
```
make BASE_IMAGE=debian:buster PYTHON=python3 TENSORFLOW_TARGET=aarch64 BUILD_DEB=y docker-build
```

**Comment by dpsm** [comment]
@Namburger  works great! thanks for your support!

**Comment by Namburger** [comment]
@dpsm No problems, thanks for the confirmation!

**Comment by ankitmaurya001** [comment]
Hi @Namburger @dpsm can you please share the steps to  build tflite_runtime whl with TF ops support for edge TPU?
