### ISSUE TITLE
USB accelerator stops working after the second process tries to use it.

### ISSUE THREAD

**Issue by YijinLiu** [google-coral/edgetpu#237]
The first process crashes with "HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]"
The LED on the accelerator flashes when this happens. I have to unplug and plug it to make it work again.
Is there any way to avoid this? For example, fail the second process instead of crashing the first one and refuse to work any more.

**Comment by Namburger** [comment]
@YijinLiu May I ask what were you running when this happens and any code to reproduce?

**Comment by YijinLiu** [comment]
I run it on ubuntu 18.04.5/5.4.0-51-generic
The code is here https://github.com/YijinLiu/tf-cpu/blob/master/benchmark/classify_lite.cc
Thanks!

**Comment by Namburger** [comment]
@YijinLiu Oh wait, sorry, I just realized that you said there was a second process trying to use it on the title, this is expected behavior. The linux kernel doesn't allow multiple processes trying to access the same usb resource, I believe this happens due to libusb and it's not something we can fix with libedgetpu. In the same fashion, this is also why we can't allow multi threading on the same tpu

**Comment by YijinLiu** [comment]
I understand that part. However, can you add a global lock or sth. like that to make it's the second process fail instead of crashing the first one? Just sth. like when you run apt.
