### ISSUE TITLE
Does tflite_runtime support multiprocessing?

### ISSUE THREAD

**Issue by hamhochoi** [google-coral/edgetpu#246]
Hi, 

Currently I want to speedup my code run yolov3-tiny for object detection on TPU by using ```multiprocessing``` or ```multithreading``` in python. 

As I tried ```multithreaing```, the performance when running more threads is worst than single thread. I also tried to use ```multiprocessing Pool``` but the code stop right before function call ```interpreter.invoke()```. 

Have anyone had tried to multiprocessing inference before and give me some advices? 

Here is my code:
```
def inference(interpreter, img):
    ...
    input_details, output_details, net_input_shape = get_interpreter_details(interpreter)
    img = np.expand_dims(img, 0)
    interpreter.set_tensor(input_details[0]['index'], img)
    # Stop right here
    interprete.invoke()
    #  Do not run the rest of the code
```

My environment: 
Linux 16.04 (arm)
Coral TPU USB Accelarator
python3.5.2
tflite_runtime 2.1.0post

Also, in [https://www.tensorflow.org/lite/performance/best_practices#tweak_the_number_of_threads](url)  it is said that I can tweak the number of threads but it seems that this version of tflite_runtime doesn't support ```set_num_threads()``` function?

Thanks,

**Comment by usbguru** [comment]
Hi @hamhochoi,
Python multiprocessing is hard to do with Tensorflow.  You can find some ideas here: https://stackoverflow.com/questions/36610290/tensorflow-and-multiprocessing-passing-sessions

If you have more than one edge TPU, you can pipeline the ML to speed up the inference time: https://coral.ai/docs/edgetpu/pipeline/

When TFlite runs on a CPU, it might be an advantage to run a number of threads to spread the computation over multiple CPU cores.  Running TFlite on the edge TPU does not benefit from multiple threads because there is only one ML core inside the edge TPU.

**Comment by hamhochoi** [comment]
Thanks for your respond. I'll try your links.
