### ISSUE TITLE
How to check TPU status, i.g. busy or idle?

### ISSUE THREAD

**Issue by carllhsiung** [google-coral/edgetpu#277]
I found that multiple programs **can't** open same TPU device (`/dev/apex_0`) at one time.

The `edgetpu::EdgeTpuManager::GetSingleton()->OpenDevice(...)` will return nullptr.

Correct me if I'm wrong.

There are multiple programs need TPUs in our system.

I can check TPU by using:

```
cat /sys/class/apex/apex_0/is_device_owned
cat /sys/class/apex/apex_0/device_owner
```

How to get TPU usage (similar to top or htop tool for CPU/RAM)?

I can show which program blocks TPU with low usage on UI if I can get TPU usage.

BTW, is there a TPU profiling tool for optimizing model, i.g. I can use [trtexec profiling](https://github.com/google-coral/edgetpu/issues/277) to find which layer takes longer time.

Thanks in advance.

**Comment by Namburger** [comment]
@car1hsiung Hello,
unfortunately we don't support concurrent access to the edgetpu at the same time and we don't have a tool currently to show the tpu usage.  If you are planning to run multiple model with only one tpu, you'll nee to ensure that the Invoke() calls happens sequencially, similar to this: https://github.com/google-coral/libcoral/blob/master/coral/examples/two_models_one_tpu.cc

If you want to have completely separate processes, then `/sys/class/apex/apex_0/is_device_owned` should tells you if the tpu is currently being used. Otherwise we do suggest that you use more than one tpu so that each process can own a tpu

**Comment by usbguru** [comment]
@car1hsiung 
Profiling a model is a common question.  Although the edge TPU doesn't have specific profiling registers, it is possible to take measurements and compute estimates.  You can see the difference between loading time and inference time in this example: https://coral.ai/docs/dev-board/get-started/#6-run-a-model-using-the-pycoral-api    The first time is longest because the model must be transferred over the PCIe bus.  The subsequent inference times are short because that is measuring only the edge TPU.  

     Look at the benchmarks: https://coral.ai/docs/edgetpu/benchmarks/  That code and data is available for your own measurements.  Remove a layer from one of the models, and see how the time changes.  Double a layer and see how the time changes.  Each model utilizes the edge TPU in a different way.  It could also be useful to run the TFlite profiling tools on these models and compare the differences:  https://www.tensorflow.org/lite/performance/best_practices    Are the performances of the edge TPU results proportional to the performance results with the TFlite profiler?

How much RAM is being used in the edge TPU?  The edgetpu_compiler will tell you:  https://coral.ai/docs/edgetpu/compiler/#performance-considerations

**Comment by carllhsiung** [comment]
I will work on it.

One more question here: Does USB Coral have device nodes, `device_owner` and `device_owner`?

I can't find them in `/sys/bus/usb/devices/2-2`.

Thank you for your quick reply.
