### ISSUE TITLE
Streaming a custom (regression) model on a server

### ISSUE THREAD

**Issue by bayntun** [google-coral/edgetpu#289]
Hi there, I've been using the coral dev board for a couple of months now, and I'm still pretty new to using gstreamer for inferencing and overlay simultaneously.  I'm currently using a modified version of edgetpuvision on the dev board but I've run into a couple of problems.  The first one is I can't seem to install edgetpuvision without breaking PyCoral on the dev board.  The second is that upon running my custom edgetpuvision, I'm getting the error:

gi.repository.GLib.GError: gst_parse_error: could not set property "filter" in element "glfilterbin0" to "glbox"

I know that glbox is not installed as a filter in gstreamer but I can't seem to install it manually.  I can get it installed by installing edgetpu Python, but I also know this is deprecated.  Can you suggest the best course of action to make a custom gstreamer server using a custom model and PyCoral API?  Thanks!

**Comment by Namburger** [comment]
Hello @bayntun since the edgetpu API was deprecated, it is necessary to run the newest edgetpuvision package that we upgraded to pycoral. Since you mentioned that you are using a modified version of it, I'm guessing that it must not be the latest version, you can checkout the code here: 
https://coral.googlesource.com/edgetpuvision/+/refs/heads/master/edgetpuvision/
