### ISSUE TITLE
Another "Internal compile error. Aborting!"

### ISSUE THREAD

**Issue by johannes-do** [google-coral/edgetpu#309]
I have the issue with this specific model:
[model_quant.tflite.zip](https://github.com/google-coral/edgetpu/files/5925349/model_quant.tflite.zip)

Tensorflow 2.2
Edge TPU Compiler version 15.0.340273435

But on an unspecific note, this error message is one of the biggest pain points I have with the whole EdgeTPU development (mostly it is really nice!). But it basically says nothing. Randomly changing filter sizes, input sizes, layer numbers seems to magically fix things, sometimes. Sometimes even just retraining the same model.
Usually, I have to decrease these kinds of parameters. Is there a size limit of parameters or such for the compiler?

I really would wish for a better error message.

**Comment by Naveen-Dodda** [comment]
Hi @j-o-d-o,

Yes you are right size of the layers is the limiting factor here. 
For example the model you shared is rejected due to large concat operation ( 60 x152 x 90). Changing filter sizes, input sizes, layer numbers will reduce the size of layers and fit on chip memory of edgetpu. 

Current version of Quantization aware training in TF2.0 would introduce some quantise and dequantise layers with float data type which will break the compiler. With TF2.0 Post training quantization is recommended. 

We can your feedback to the team about more detailed error messages.

**Comment by johannes-do** [comment]
Cool, thanks for the quick response. Something like this would be nice as an error message. Then we don't have to create a github issues everytime this happens :)
Is there some documentation which operations we can assume are "too large"? Otherwise checking for every configuration is a bit tedious and it is hard to find the optimal sizes that still work. Here it says that if on-chip memory is not enough it will use RAM (https://coral.ai/docs/edgetpu/compiler/#performance-considerations), shouldn't this apply to that issue?

Also I tested with Tensorflow 2.4 and get "Model not quantized".

So the takeaway for me is: 
- Stick to Tensorflow 2.2
- Make sure operations are not too large 
- Edit: Tensorflow 2.4 seems to work ok with `experimental_new_converter = False`
