### ISSUE TITLE
Edge TPU cannot do constant multiplication

### ISSUE THREAD

**Issue by wuhy08** [google-coral/edgetpu#35]
Consider a very simple model: `output=0.1*input`. After building model in tf.keras -> convert and quantize using tflite converter -> comiple using edgetpu_compiler. I found out that the last step failed.

I think it turned out that `tf_op_layer_Mul` in tensorflow is not supported in edgetpu_compiler. The op is invoked when broadcasting is needed. 

Please see the following quantized model files for references:

[test_linear_mul_layer.zip](https://github.com/google-coral/edgetpu/files/3990579/test_linear_mul_layer.zip)

**Comment by Namburger** [comment]
Hi @wuhy08 could you specify which tensorflow version are you using to create the model? What's the difference between "direct" and non direct in your case?

**Comment by wuhy08** [comment]
Hi, I am using tf-nightly, which was updated last Friday. I don’t remember for sure but one is using output=0.1*input, the other is using output=Layers.Multiply(input, tf.constant([0.1]))

**Comment by Namburger** [comment]
@wuhy08 
I see,
Is it [recommended](https://coral.ai/docs/edgetpu/models-intro/#quantization) that you use tf1.15 for now since we are still working on compiler support for tf2.0 at the moment. Both of the models compiled with our internal compiler which means these models will compile once we release. This is fixed along with our effort to integrate with tf2.0.
Unfortunately we don't have a release date at the moment.

**Comment by wuhy08** [comment]
Thank you for the quick reply! Happy holidays!

**Comment by Namburger** [comment]
@wuhy08 thanks, you too!!
