### ISSUE TITLE
Coral USB Accelerator: silicon shortage or end of production?

### ISSUE THREAD

**Issue by ricardodeazambuja** [google-coral/edgetpu#363]
I'm trying to answer the question above, but searching on Google I got nothing. Everywhere I checked (e.g. all the links from coral.ai website) the stocks are zero. So, I'm wondering whether Google is killing the USB Accelerator...

Thanks in advance for any clues!

**Comment by wb666greene** [comment]
I hope not, unless they are coming up with a new version to support full tensorflow models.  

The M2 modules are nice and priced much lower (< 1/2), but my initial experience with them has not been as smooth as with the USB version -- see issues #361 and #362  

Not to mention that M2 slots are not common in IOT class machines at the moment, and ones that do (Pi CM4 & nanoPC) has open issues here about using the modules, see issues #280 & #140 for example.

**Comment by mbrooksx** [comment]
This is a silicon shortage (the same as everyone else in the industry is dealing with right now). We are currently building as many as we can - we have recently completed and shipped a new batch  that should be available with our distribution partners shortly.

**Comment by lairdm** [comment]
It looks like that batch sold out very quickly, which isn't at all surprising. @mbrooksx, may I ask if you know when the next batch might be shipping to distributors? Thank you again for taking the time to answer these questions, it's very much appreciated.

**Comment by tbgoose** [comment]
@mbrooksx, any update if we will be seeing more of these? I haven't seen any in stock for a long time now, and have never really had the chance to buy one being in Australia.

**Comment by hjonnala** [comment]
@tbgoose We have a small shipment of USB modules to some retailers such as OKDo and Pi3g this month. It's possible that there are already long waiting lists at the retailers.

We recommend to place a pre order with Mouser or other retailers and wait for delivery. 

Thanks!

**Comment by tbgoose** [comment]
I placed an order with RS components in August last year. They've continued
to push delivery dates out as they approach and are now saying expected
stock end of July 2022. Fingers crossed...

**Comment by wb666greene** [comment]
I placed an order with Mouser in Oct 2021, its been pushed back to Aug 2022.

It's time to start considering Plan B.

**Comment by tbgoose** [comment]
Probably is, it's not even properly listed on mouser AU to be able to place
a pre-order there. What is plan b? Get a whole SoC board just for TPU edge
processing?

My use case was for frigate detection on my rpi4 home assistant setup. The
USB is just perfect for that.

**Comment by wb666greene** [comment]
Unfortunately for the Pi4 class systems there doesn't seem to be any alternative.  The Movidius NCS2 is far inferior to the Coral TPU accelerators for my purposes.  If you only need a single camera input, perhaps the OAK cameras with integrated MyraidX could fill the bill.  The Jetson Nano and TensorRT seems the best option I'm aware of in the Pi4+TPU price range.  See the Nano TensorRT blogs of JK Jung to evalute if the Nano could  work for you.

If I can solve the thermal issues, I'm getting great results with MobilenetSSD_v2 for person detection on a Nano using an A+E Key TPU module (~15 fps round robbin with five 4K cameras, limitation is rtsp stream decoding, not TPU inference rate) and TensorRT based yolov4 as a verification step on detections to further push the false positive rate towards zero.  Get about 4 fps for the verification which so far works out OK since most frames in security system usage don't have people in them.

Mouser seesm to have a couple of thousand Coral Developement boards apparently in stock as of a few minutes ago.  It is in the price ballpark of a Pi4B + TPU but the Mendel software system it uses is a lot more work to get going compared to Raspbian on the Pi or Ubuntu on the Nano.  I did run my MobilenetSSD_v2 on the Coral Development board and it works great for HD cameras getting about 20 fps without display round robin for 8 1080p camers, but it chokes on 4K streams with 2 or 3 cameras being about it.

While I can buy more Nano there are no TPU to be found.

**Comment by swami23** [comment]
arrow.com is apparently has a lot of stock and selling at 3x the price ... gouging...

**Comment by ricardodeazambuja** [comment]
> The Movidius NCS2 is far inferior to the Coral TPU accelerators for my purposes.

@wb666greene, I know this is an old message, but I am curious and I would like to ask you why do you consider the NCS2 far inferior to the Coral TPU. I've been using an OAK-D Lite (same Movidius Myriad X as the NCS2, afaik) and I would say it's quite good, therefore I would expect a NCS2 connected to something like a RPI4 to be even better. Thanks!

**Comment by wb666greene** [comment]
My benchmark is frame rate using MobileNetSSD_V2 trained on the coco data set with USB3 TPU or NCS2 coprocessors.  The TPU uses Google's downloadable coefficients, the NCS2 uses the model converter to make the coefficients.  The OAK camera improves things quite a lot because the image data doesn't have to cross the USB3 bus.  But 1 co=processor per camera is not cost effective for my system.  Hence I round-robin sample the cameras and feed the images to the co-processor.
