### ISSUE TITLE
Internal compiler error. Aborting!

### ISSUE THREAD

**Issue by ZhouKai90** [google-coral/edgetpu#378]
Error message:
edgetpu_compiler tiny_yolov4_540_960.tflite
Edge TPU Compiler version 14.1.317412892

Internal compiler error. Aborting!

Edge TPU Compiler version: both 14.1.317412892 and 15.0.340273435
TensorFlow version:2.3.0

[tiny_yolov4_540_960.tflite.zip](https://github.com/google-coral/edgetpu/files/6451135/tiny_yolov4_540_960.tflite.zip)

**Comment by Naveen-Dodda** [comment]
@ZhouKai90 

I can see that it fails with 15.0. Can you please share your quantization script and a saved model, to further debug this.

**Comment by ZhouKai90** [comment]
@Naveen-Dodda 
Thanks for your reply. Here is the detail above.
[https://drive.google.com/drive/folders/1FGFKE8k9ZczO_JmiQCBzaZDWf9XgK9gC?usp=sharing](url)

**Comment by ZhouKai90** [comment]
@Naveen-Dodda 
May I ask what progress this thing?

**Comment by Naveen-Dodda** [comment]
@ZhouKai90 This issue cannot be fixed with tflite_convert. It was issue with external version of edgetpu_compiler. But i was able to compile it successfully with internal compiler. 
So this issues would be fixed with next release of compiler. 

I mean time do you want a compiled version of this model or instead will you explore another model ?

**Comment by ZhouKai90** [comment]
@Naveen-Dodda
Yes, share me the compiled version of this model, please.

**Comment by Naveen-Dodda** [comment]
[tiny_yolov4_540_960.tflite.tar.gz](https://github.com/google-coral/edgetpu/files/6497651/tiny_yolov4_540_960.tflite.tar.gz)
