### ISSUE TITLE
Fedora packages

### ISSUE THREAD

**Issue by indrora** [google-coral/edgetpu#43]
Currently, there are only Debian packages available. Given that quite a few data science organizations typically run on Fedora, given the ease of use for SciPy and friends, can we get a few Fedora releases made available?

**Comment by Namburger** [comment]
@indrora  I understand your query! Although I do not believe we have rpm packages in our road map (although I'll raise this up on our weekly meeting), we do have most of the needed packages on our github page as binaries. I have not tested this (since I don't have a Fedora machine currently), but doing this should work:

I'm taking that you'll be using the USB Accelerator for your host machine? If so these would be the packages you'll need/want:
* edgetpu-compiler
* libedgetpu-dev && (libedgetpu1-std || libedgetpu1-max)
* python3-edgetpu && edgetpu-examples
All of these packages are documented here: https://coral.ai/software/

1) Using the edgetpu compiler:
The current release of the compiler is hosted here (you can pick the architecture):
https://github.com/google-coral/edgetpu/tree/master/compiler

2) libedgetpu runtime:
The runtime library are hosted here as .so file. We do not have static lib currently.
https://github.com/google-coral/edgetpu/tree/master/libedgetpu

The 'throttle' and 'direct' corresponds to libedgetpu1-std and libedgetpu1-max and the .c/.h files are for libedgetpu-dev.
You can just copy those file to the location that you want or use our provided script to install them:
https://github.com/google-coral/edgetpu/blob/master/scripts/runtime/install.sh

3) These packages are basically our provided edgetpu api for running inferences and some examples.
You can get them from here: (python3-edgetpu)[https://github.com/google-coral/edgetpu/tree/master/edgetpu]
and here: (examples)[https://github.com/google-coral/edgetpu/tree/master/examples]

**Comment by mrshu** [comment]
Hey @Namburger,

I realize that you've closed this issue a couple days ago but in the meantime, I was able to both install the `edgetpu` packages and successfully run inference on Coral from within Fedora 30.

If time permits, I'll try to create a quick package that would automate the steps I have had to do manually.

Thanks!

**Comment by mskarbek** [comment]
I'm also interested in RPM packages including DKMS for the M.2 version of Coral and I would like to help with packaging.

**Comment by Namburger** [comment]
@mrshu @mskarbek 
Thanks for updating the issue. As I explained previously, everything you need to get working with centos should be here: coral.ai/software so I won't reiterate unless you have additional question, feel free to ask.

As for the DKMS module, that is a little more complicated since it is a kernel module...
The driver's source in [open source](https://coral.googlesource.com/linux-imx/+/refs/heads/release-day/drivers/staging/gasket) which you can grab. I'm not sure if there's a clean way to do it, but with apt package you can download and manually install with something like this:
```
1) Download the deb package:
```
$ apt download gasket-dkms (download the deb package)
```
2) Unpack and change dir:
```
$ dpkg-deb -R gasket-dkms_1.0-10_all.deb gasket && cd gasket
```
3) Copy the src to the correct name/location:
```
$ sudo cp -r usr/src/gasket-1.0 /usr/src/gasket-dkms-1.0
```
4) Finally, add and install the driver:
```
$ sudo dkms add gasket-dkms-1.0 --kernelsourcedir=/usr/src/linux-headers--$(uname -r)
$ sudo dkms install gasket-dkms-1.0 --kernelsourcedir=/usr/src/linux-headers--$(uname -r)"
```
Obviously step 1 and 2 won't be available to you but you can just grab the source from the link above, what I copied in step 3 (usr/src/gasket-1.0) are the source code on that link. You'll need the `linux-headers` package as it is a dependencies. Sorry, I'm not able to test this on my debian machine so I can't give exact steps or can ensure if this will work. keep us updated if you found success with this method!

**Comment by ryanm101** [comment]
@mrshu @mskarbek did either of you get it working? I've NUC with fedora 34 and the M2 tpu..

**Comment by mrshu** [comment]
@ryanm101 I sadly was not -- I still think it should not be such a big deal though :)

**Comment by ryanm101** [comment]
ahh no worries, i just rebuilt it with debian.

**Comment by raintonr** [comment]
See: https://copr.fedorainfracloud.org/coprs/robertzaage/gasket-dkms/

**Comment by cyqsimon** [comment]
And for RHEL & SUSE users, there is also https://copr.fedorainfracloud.org/coprs/kylegospo/google-coral-dkms/

**Comment by ryanm101** [comment]
Has anyone had anyluck with the usb coral on fedora. My M.2 PCIe works brilliantly with https://copr.fedorainfracloud.org/coprs/kylegospo/google-coral-dkms/ but my usb one shows as `Bus 003 Device 002: ID 1a6e:089a Global Unichip Corp. [unknown]`

**Comment by ryanm101** [comment]
Note: https://www.clarenceho.net/2023/05/using-google-coral-tpu-on-opensuse.html looks like it might do the trick

**Comment by lunakoa** [comment]
> Has anyone had anyluck with the usb coral on fedora. My M.2 PCIe works brilliantly with https://copr.fedorainfracloud.org/coprs/kylegospo/google-coral-dkms/ but my usb one shows as `Bus 003 Device 002: ID 1a6e:089a Global Unichip Corp. [unknown]`

I am the opposite, I started using the Coral USB first then added the PCIe (M.2) later, only the USB works not the M.2 version.

Still researching, trying to uninstall and reinstall see if that helps.

**Comment by mwprado** [comment]
> Has anyone had anyluck with the usb coral on fedora. My M.2 PCIe works brilliantly with https://copr.fedorainfracloud.org/coprs/kylegospo/google-coral-dkms/ but my usb one shows as `Bus 003 Device 002: ID 1a6e:089a Global Unichip Corp. [unknown]`

It is working on my laptop (m2 version https://coral.ai/docs/m2/get-started/#requirements) whith KyleGospo/gasket-dkms module. Now I searching for libedgetpu.




$ lspci
06:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU

**Comment by mwprado** [comment]
I got to build libedgetpu with bazel6 in fedora but I don't know how to build packages or create a spec file for bazel builds.

**Comment by mwprado** [comment]
I got compile using Makefile only at fedora 40.

Needs change Makefile with new flags, correct common.c reference in makefile_build folder.

Command:
$ TFROOT=/download_folder/tensorflow-2.16.1 make


[new_makefile.patch.txt](https://github.com/user-attachments/files/17036490/new_makefile.patch.txt)

**Comment by ctml91** [comment]
I am trying to get the Coral USB to be detected on Fedora CoreOS (IoT) 41. I am planning to use this with frigate running in a container. So far I haven't had any success, the USB is not detected by the host at all. Any tips would be appreciated.

> Note: https://www.clarenceho.net/2023/05/using-google-coral-tpu-on-opensuse.html looks like it might do the trick

Did you have any luck getting the Coral USB working on Fedora?
