### ISSUE TITLE
edge_tpu-compiled model file is 2 time larger than the base file

### ISSUE THREAD

**Issue by Wirg** [google-coral/edgetpu#463]
Hello !

Thank you for the coral products ! :)

### Description

When I compile my tflite model to edge_tpu, the produced file is more than 2 time bigger.
Is this an expected behavior ? How can I work to improve this ?

![image](https://user-images.githubusercontent.com/17848620/132324125-04be7181-d981-42d6-920d-a30b05c411dc.png)

<details><summary>Click to expand!</summary> 

### Issue Type

Performance

### Operating System

Ubuntu

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

</details>

**Comment by hjonnala** [comment]
Hi @Wirg can you please share 7.6MB quatized_size_224.tflite model?

**Comment by Wirg** [comment]
Hi !

Thank you for answering so fast. :)

Here is an equivalent with a smaller version :
![image](https://user-images.githubusercontent.com/17848620/132406982-0c35cee8-559a-4e81-b0d2-51c552cbab7a.png)


[outputs.zip](https://github.com/google-coral/edgetpu/files/7124195/outputs.zip)

**Comment by RobertChenKFC** [comment]
I'm also having a similar problem with exploding model sizes, not sure if it's the same issue. [Here](https://github.com/google-coral/edgetpu/files/7134760/models.zip) is the CPU tflite model and the compiled tflite model. The following are their model sizes:
```
1.3M	quant_model.tflite
22M	quant_model_edgetpu.tflite
```

**Comment by Wirg** [comment]
Hi !

I am looking for an update on this.
Is this an expected behavior ?
In which ratio range should I expect my edgetpu.tflite to be compared to the original one ? (+- 20% ?)

How can I know the real inpact on the edgetpu RAM / cache when loaded ?

**Comment by hjonnala** [comment]
There is no fixed ratio that we can compare with the original one. It really depends on operations and their sizes it is mapped to edgetpu. And lib edgetpu reserves memory on cpu to stream outputs (which varies depending size and type of output)

For your model please try below commands: 
We can see same number of operations mapped to edgetpu but the output size differ by 6MB.

If inference time and accuracy are not satisfactory  please experiment with different intermediate sensors or different operation sizes and compare the accuracy and inference time.
```
! edgetpu_compiler -s -i model_3/yolact/concat_1 quantized_size_224.tflite

Input size: 6.25MiB
Output model: quantized_size_224_edgetpu.tflite
Output size: 16.83MiB
On-chip memory used for caching model parameters: 4.98MiB
On-chip memory remaining for caching model parameters: 54.25KiB
Off-chip memory used for streaming uncached model parameters: 11.25MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 105
Operation log: quantized_size_224_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 77
Number of operations that will run on CPU: 28
```
```
! edgetpu_compiler -s -i model_3/detect/decode_boxes/decode_boxes/concat/axis  quantized_size_224.tflite

Input size: 6.25MiB
Output model: quantized_size_224_edgetpu.tflite
Output size: 10.58MiB
On-chip memory used for caching model parameters: 5.02MiB
On-chip memory remaining for caching model parameters: 6.50KiB
Off-chip memory used for streaming uncached model parameters: 5.22MiB
Number of Edge TPU subgraphs: 1
Total number of operations: 105
Operation log: quantized_size_224_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 77
Number of operations that will run on CPU: 28
```

**Comment by hjonnala** [comment]
@RobertChenKFC I have tested quant_model.tflite with all intermediate tensors layers. I don't see any major jump in output size when adding more layers to edgetpu.
 
[quant_model.csv](https://github.com/google-coral/edgetpu/files/7187052/quant_model.csv)

**Comment by RobertChenKFC** [comment]
@hjonnala Even though there aren't any major jumps in output sizes when adding more layers to the edge TPU, I wasn't expecting the model size to increase at all. I modified the csv file you provided, keeping only the StridedSlice immediate tensors. Please take a look at the table below:
|Intermediate layer name           |Input size|Output size|On-chip memory used for caching model parameters|On-chip memory remaining for caching model parameters|Off-chip memory used for streaming uncached model parameters|Number of Edge TPU subgraphs|Total number of operations|Number of operations that will run on Edge TPU|Number of operations that will run on CPU|output|
|----------------------------------|----------|-----------|------------------------------------------------|-----------------------------------------------------|------------------------------------------------------------|----------------------------|--------------------------|----------------------------------------------|-----------------------------------------|------|
|sequential_1/rnn_1/StridedSlice   |1.23MiB   |1.50MiB    |48.00KiB                                        |7.69MiB                                              |0.00B                                                       |1.0                         |449.0                     |83.0                                          |366.0                                    |1.5   |
|sequential_1/rnn_1/StridedSlice_1 |1.23MiB   |2.29MiB    |918.00KiB                                       |6.84MiB                                              |0.00B                                                       |1.0                         |449.0                     |96.0                                          |353.0                                    |2.29  |
|sequential_1/rnn_1/StridedSlice_2 |1.23MiB   |3.06MiB    |1.65MiB                                         |6.09MiB                                              |0.00B                                                       |1.0                         |449.0                     |109.0                                         |340.0                                    |3.06  |
|sequential_1/rnn_1/StridedSlice_3 |1.23MiB   |3.82MiB    |2.41MiB                                         |5.33MiB                                              |0.00B                                                       |1.0                         |449.0                     |122.0                                         |327.0                                    |3.82  |
|sequential_1/rnn_1/StridedSlice_4 |1.23MiB   |4.58MiB    |3.16MiB                                         |4.57MiB                                              |0.00B                                                       |1.0                         |449.0                     |135.0                                         |314.0                                    |4.58  |
|sequential_1/rnn_1/StridedSlice_5 |1.23MiB   |5.35MiB    |3.92MiB                                         |3.82MiB                                              |0.00B                                                       |1.0                         |449.0                     |148.0                                         |301.0                                    |5.35  |
|sequential_1/rnn_1/StridedSlice_6 |1.23MiB   |6.11MiB    |4.68MiB                                         |3.06MiB                                              |0.00B                                                       |1.0                         |449.0                     |161.0                                         |288.0                                    |6.11  |
|sequential_1/rnn_1/StridedSlice_7 |1.23MiB   |6.88MiB    |5.43MiB                                         |2.31MiB                                              |0.00B                                                       |1.0                         |449.0                     |174.0                                         |275.0                                    |6.88  |
|sequential_1/rnn_1/StridedSlice_8 |1.23MiB   |7.64MiB    |6.19MiB                                         |1.55MiB                                              |0.00B                                                       |1.0                         |449.0                     |187.0                                         |262.0                                    |7.64  |
|sequential_1/rnn_1/StridedSlice_9 |1.23MiB   |8.40MiB    |6.94MiB                                         |814.00KiB                                            |0.00B                                                       |1.0                         |449.0                     |200.0                                         |249.0                                    |8.4   |
|sequential_1/rnn_1/StridedSlice_10|1.23MiB   |9.17MiB    |7.70MiB                                         |40.00KiB                                             |0.00B                                                       |1.0                         |449.0                     |213.0                                         |236.0                                    |9.17  |
|sequential_1/rnn_1/StridedSlice_11|1.23MiB   |9.94MiB    |7.70MiB                                         |40.00KiB                                             |774.00KiB                                                   |1.0                         |449.0                     |226.0                                         |223.0                                    |9.94  |
|sequential_1/rnn_1/StridedSlice_12|1.23MiB   |10.70MiB   |7.70MiB                                         |40.00KiB                                             |1.51MiB                                                     |1.0                         |449.0                     |239.0                                         |210.0                                    |10.7  |
|sequential_1/rnn_1/StridedSlice_13|1.23MiB   |11.47MiB   |7.70MiB                                         |40.00KiB                                             |2.27MiB                                                     |1.0                         |449.0                     |252.0                                         |197.0                                    |11.47 |
|sequential_1/rnn_1/StridedSlice_14|1.23MiB   |12.23MiB   |7.70MiB                                         |40.00KiB                                             |3.02MiB                                                     |1.0                         |449.0                     |265.0                                         |184.0                                    |12.23 |
|sequential_1/rnn_1/StridedSlice_15|1.23MiB   |12.99MiB   |7.70MiB                                         |40.00KiB                                             |3.78MiB                                                     |1.0                         |449.0                     |278.0                                         |171.0                                    |12.99 |
|sequential_1/rnn_1/StridedSlice_16|1.23MiB   |13.75MiB   |7.70MiB                                         |40.00KiB                                             |4.54MiB                                                     |1.0                         |449.0                     |291.0                                         |158.0                                    |13.75 |
|sequential_1/rnn_1/StridedSlice_17|1.23MiB   |14.52MiB   |7.70MiB                                         |40.00KiB                                             |5.29MiB                                                     |1.0                         |449.0                     |304.0                                         |145.0                                    |14.52 |
|sequential_1/rnn_1/StridedSlice_18|1.23MiB   |15.28MiB   |7.70MiB                                         |40.00KiB                                             |6.05MiB                                                     |1.0                         |449.0                     |317.0                                         |132.0                                    |15.28 |
|sequential_1/rnn_1/StridedSlice_19|1.23MiB   |16.05MiB   |7.70MiB                                         |40.00KiB                                             |6.80MiB                                                     |1.0                         |449.0                     |330.0                                         |119.0                                    |16.05 |
|sequential_1/rnn_1/StridedSlice_20|1.23MiB   |16.81MiB   |7.70MiB                                         |40.00KiB                                             |7.56MiB                                                     |1.0                         |449.0                     |343.0                                         |106.0                                    |16.81 |
|sequential_1/rnn_1/StridedSlice_21|1.23MiB   |17.57MiB   |7.70MiB                                         |40.00KiB                                             |8.31MiB                                                     |1.0                         |449.0                     |356.0                                         |93.0                                     |17.57 |
|sequential_1/rnn_1/StridedSlice_22|1.23MiB   |18.34MiB   |7.70MiB                                         |40.00KiB                                             |9.07MiB                                                     |1.0                         |449.0                     |369.0                                         |80.0                                     |18.34 |
|sequential_1/rnn_1/StridedSlice_23|1.23MiB   |19.10MiB   |7.70MiB                                         |40.00KiB                                             |9.83MiB                                                     |1.0                         |449.0                     |382.0                                         |67.0                                     |19.1  |
|sequential_1/rnn_1/StridedSlice_24|1.23MiB   |19.87MiB   |7.70MiB                                         |40.00KiB                                             |10.58MiB                                                    |1.0                         |449.0                     |395.0                                         |54.0                                     |19.87 |
|sequential_1/rnn_1/StridedSlice_25|1.23MiB   |20.63MiB   |7.70MiB                                         |40.00KiB                                             |11.34MiB                                                    |1.0                         |449.0                     |408.0                                         |41.0                                     |20.63 |
|sequential_1/rnn_1/StridedSlice_26|1.23MiB   |21.39MiB   |7.70MiB                                         |40.00KiB                                             |12.09MiB                                                    |1.0                         |449.0                     |421.0                                         |28.0                                     |21.39 |
|sequential_1/rnn_1/StridedSlice_27|1.23MiB   |21.41MiB   |7.70MiB                                         |40.00KiB                                             |12.85MiB                                                    |1.0                         |449.0                     |434.0                                         |15.0                                     |21.41 |

As you can see, the output model size increases by about 0.77MiB when we change the immediate tensor from one StridedSlice operation to the next. Moreover, when we change the immediate tensor to the next StridedSlice operation, 1 additional FullyConnected operation is added to the edge TPU, whose weights and bias shapes are (1536, 512) and (1536,), respectively.

Since all model parameters are quantized, each floating point should take 1 byte, thus the weights and bias of the FullyConnected operation should take up `(1536 * 512 + 1536) / 1024 / 1024 = 0.75...` MiB, which is close to the 0.77MiB increase in model size we saw when changing to the next StridedSlice operation. However, I don't think there should be an increase in model size, since all these weights and biases are exactly the same among different FullyConnected operations (which is also why the CPU tflite model is so small compared to the edge TPU one). Therefore, it seems to me that the `edgetpu_compiler` is duplicating the model parameters even when it should not. Please let me know if this is the intended behavior or a bug in the `edgetpu_compiler`. Thank you.

**Comment by RobertChenKFC** [comment]
@hjonnala I would like to know if there is any update on this, thanks.

**Comment by hjonnala** [comment]
Hi, compiler doesn't duplicate weights,  this is the intended behavior. Thanks!
