### ISSUE TITLE
USB devices are not auto detected after start until plugged

### ISSUE THREAD

**Issue by asmirnou** [google-coral/edgetpu#523]
### Description

UVC-Compliant USB 2.0 camera connected to USB 2.0 Type-C OTG connector on Coral Dev board mini is recognised well only when plugged. After dev board reboots the device is no longer detected until re-plugged. 

I've tried resetting USB device, re-binding USB bus, triggering UDEV service - all to no avail, nothing helps until physically reconnect the device. I also tested with another peripheral device - an Android smartphone - which led to the same problem: the phone is listed in `lsusb`, but disappears after rebooting dev board.

USB-C port of the camera is configured as OTG-slave, dev board always provides 5V power supply to the peripheral device. 

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Relevant Log Output

```shell
AFTER BOOT
mendel@jumping-horse:~$ lsusb
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp. 
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

AFTER PLUGGING 1
mendel@jumping-horse:~$ lsusb
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp. 
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 010: ID 0c45:636d Microdia 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

AFTER PLUGGING 2
mendel@jumping-horse:~$ lsusb
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp. 
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 011: ID 04e8:6860 Samsung Electronics Co., Ltd Galaxy series, misc. (MTP mode)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
</details>

**Comment by oriyaish** [comment]
I am also struggling this issue.
Did you find a solution?

Thanks

**Comment by manoj7410** [comment]
@asmirnou Which Mendel version are you working with?

**Comment by asmirnou** [comment]
the latest, 5.3

**Comment by oriyaish** [comment]
@manoj7410 
@asmirnou 

It is also the situation in 5.0

**Comment by dave-andersen** [comment]
Noting that this is still a problem at the end of March, with a different USB device. (And one that's a blocker for us.). Also on 5.3. It means we can't connect a cellular modem to the board.

**Comment by hjonnala** [comment]
It is the expected behavior. The USB-C port is set to OTG, and the mode detection is triggered at the plug/unplug interrupt https://coral.googlesource.com/linux-mtk/+/refs/heads/master/drivers/usb/musb/mediatek.c#277 . (Reboot is not an interrupt event)

To have the USB port stick to the host mode, please change the dts https://coral.googlesource.com/linux-mtk/+/refs/heads/master/arch/arm64/boot/dts/mediatek/mt8167-coral.dts#766 to be default to "host" https://coral.googlesource.com/linux-mtk/+/refs/heads/master/drivers/usb/common/common.c#100, and rebuild the linux kernel image.

Here are the instructions to rebuild the image: https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md. 

**Please note that,** When the default dr_mode is changed to "host", that port can no longer be used as the mdt port to communicate with the host machine via the USB cable. You will need to use the debug UART port from the 40-pin header to communicate with the board or use ssh.

Thanks!

**Comment by dave-andersen** [comment]
Thank you. This worked perfectly.

**Comment by MostHated** [comment]
I am having USB issues where I can't get an external USB SSD to be detected. 

```sh
➜  ~ cat /etc/mendel_version
5.3

OS: Mendel GNU/Linux 5 (Eagle) aarch64
Host: Freescale i.MX8MQ Phanbell
Kernel: 4.14.98-imx
Uptime: 24 mins
Packages: 748 (dpkg)
Shell: zsh 5.7.1
Terminal: /dev/pts/0
CPU: (4) @ 1.500GHz
Memory: 254MiB / 985MiB

```

```sh
➜  ~ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```sh
T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 1
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=04.14
S:  Manufacturer=Linux 4.14.98-imx xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=xhci-hcd.0.auto
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=02 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=5000 MxCh= 1
D:  Ver= 3.00 Cls=09(hub  ) Sub=00 Prot=03 MxPS= 9 #Cfgs=  1
P:  Vendor=1d6b ProdID=0003 Rev=04.14
S:  Manufacturer=Linux 4.14.98-imx xhci-hcd
S:  Product=xHCI Host Controller
S:  SerialNumber=xhci-hcd.0.auto
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#=0x0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub
```

Plugging and replugging doesn't seem to do anything in the USB-A port near the ethernet port. It just always shows nothing in lsusb and usb-devices.
