### ISSUE TITLE
Differenct performance on [Desktop(Intel i7-9700 CPU) + TPU(M.2 Accelerator B+M key) ] & [RADXA Rock 3A + TPU(M.2 Accelerator A+E key)]

### ISSUE THREAD

**Issue by tingggggg** [google-coral/edgetpu#554]
### Description

Hello,

I ran the same model(mobilenet-yolov3) both on 
[Desktop(Intel i7-9700 CPU) + TPU(M.2 Accelerator B+M key) ] & 
[RADXA Rock 3A + TPU(M.2 Accelerator A+E key)].

I got the inference performance(average execution time) as

[Desktop(Intel i7-9700 CPU) + TPU(M.2 Accelerator B+M key) ]: **about 9.1 ms**
[RADXA Rock 3A + TPU(M.2 Accelerator A+E key)]: **about 36.4 ms**
_(measure the time required to execute the model only)_ 

What I want to confirm is that I use the M.2 Accelerator for both experiments, should I get about the same performance?
If not, can someone tell me what factors are affecting?

thanks~

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Linux, Ubuntu

### Coral Device

M.2 Accelerator A+E, M.2 Accelerator B+M

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@tingggggg Inference time would depends on following factors:

- Model Size
- Host operating system CPU
- Number of Operations Mapped to TPU vs CPU
- Interface b/w CPU and TPU (PCIE/USB 3.0/ USB 2.0)

In you case, it might be some operations mapped to CPU. Due to this you are getting different results. If you would like to know the time taken for CPU please try to build [libcoral](https://github.com/hjonnala/libcoral) and try the [single_model_benchmark.cc](https://github.com/google-coral/libcoral/blob/master/coral/single_model_benchmark.cc) script.

```
hemanth@hemanth:~/libcoral/out/k8/benchmarks/coral$ ./single_model_benchmark -model /home/hemanth/Downloads/ssd_mobilenet_ssd_v1_coco_quant_postprocess_edgetpu.tflite
2022-03-10 07:38:52
Running ./single_model_benchmark
Run on (4 X 3900 MHz CPU s)
CPU Caches:
  L1 Data 32K (x2)
  L1 Instruction 32K (x2)
  L2 Unified 256K (x2)
  L3 Unified 4096K (x1)
Load Average: 0.37, 0.65, 0.89
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Model         9.63 ms         1.53 ms          495 ssd_mobilenet_ssd_v1_coco_quant_postprocess_edgetpu.tflite

```

**Comment by tingggggg** [comment]
@hjonnala 
ok, I got it. I will try it.
Thanks for your help.
