### ISSUE TITLE
Change the Frequency of TPU on Dev Board

### ISSUE THREAD

**Issue by vleonn** [google-coral/edgetpu#616]
Hello, 

I know that the TPU accelerator module supports frequencies of 500MHz (default), 250MHz and 125MHz.

The question is, can you change between them on Dev Board? For example, set frequency = 250MHz.

I have not seen any relevant documentation for Dev Board.
The only information I have seen refers to the USB accelerator and the installation of the Edge TPU runtime on the host-PC (you can choose 500MHz or 250MHz when installing "libedgetpu1")

Thank you in advance.

**Comment by hjonnala** [comment]
Hello @vleonn 

Dev Board, uses SOM, is a PCIe based device. For PCIe-based devices, both packages behave the same because the PCIe driver performs [dynamic frequency scaling](https://coral.ai/docs/pcie-parameters/#use-dynamic-frequency-scaling) to adjust the operating frequency based on programmable temperature thresholds.

Please note that, You **cannot manually specify the Edge TPU operating frequency** for Coral PCIe devices. The Coral PCIe driver always runs the Edge TPU at the maximum frequency (500 MHz), **except when it's reduced by DFS**, as described [here](https://coral.ai/docs/pcie-parameters/#use-dynamic-frequency-scaling).

Thanks!

![image](https://user-images.githubusercontent.com/86132058/175790697-4ee088ae-a62e-4a8c-aa40-cda223ad9dd6.png)
