### ISSUE TITLE
Batch size > 1

### ISSUE THREAD

**Issue by dacquaviva** [google-coral/edgetpu#700]
### Description

I am trying to compile an ssd_mobilenet_v2_320x320_coco17_tpu-8 from the [TF Object detection API ](https://github.com/tensorflow/models/tree/master/research/object_detection). I am able to do it using batch size 1, therefore i first convert the tf saved_model to tflite and then i compile for edge tpu. However, i am not able to replicate same steps if batch size > 1, i don't find anything in the documentation or much online therefore i am asking here.

Does tflite and therefore also edgetpu support bacth size > 1?, I'd like to fix it before compilation and therefore not pass one image at the time looping over them. 

Thanks fir the support!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Ubuntu

### Coral Device

Mini PCIe

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
TPU can suports only upto 3 [innermost dimensions](https://coral.ai/docs/edgetpu/models-intro/#model-requirements).  You may try making batch size >1 with the grey scale image to compile the model: https://github.com/google-coral/edgetpu/issues/30#issuecomment-587288439. Otherwise batch size > 1 is not supported. Thanks!
