### ISSUE TITLE
Auto-boot Coral Dev Board Mini over GPIO Pins

### ISSUE THREAD

**Issue by tsuijten** [google-coral/edgetpu#706]
### Description

I would like to be able to power the Coral using the GPIO pins. When power is applied it should start automatically. Currently if I apply power to a +5V pin I still have to press the power button for the Coral to turn on. Is these any way to have the Coral boot automatically when power is applied to the 5V pin?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request, Others

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @tsuijten  Automatically booting Dev Board Mini with GPIO pins is not supported.

**Comment by tsuijten** [comment]
> Hi @tsuijten Automatically booting Dev Board Mini with GPIO pins is not supported.

@hjonnala is it possible to change the power-button behaviour in the firmware / bootloader or something?

**Comment by hjonnala** [comment]
Unfortuantley, No.It would require hardware change like shortening the power button or controlling with some Microcontroller Unit..

**Comment by tsuijten** [comment]
@hjonnala Thanks for you reply. Just to give you some context, we have 50 DevBoard Mini's on stock and we are integrating that with our custom board. We want to automatically power on the Coral and have a spare USB-C port for connecting an external device.

I tried shorting the power button, but it seems like the Coral then turned off again after 20 seconds, is there som kind of long-press logic to the power button?

If you have any other idea, would be greatly appreciated! Thanks.

**Comment by hjonnala** [comment]
I have checked with internal team on the electrical side of things, came to know that there's no possibility to power through the header, but that if user can set up something that just quickly shorts the power button instead of keeping it shorted, that should work -- since long press is what causes shutdown

Please have a good to look into this: https://coral.googlesource.com/linux-mtk/+/refs/heads/master/Documentation/devicetree/bindings/input/mtk-pmic-keys.txt

mt6392 is our PMIC, so it seems like this may be able to change the long-press behavior, but I don't have any additional steps on how to do that as we haven't ever looked into it. Thanks!

**Comment by yaroslavdu** [comment]
@tsuijten Hi! Have you succeeded with your intention to boot and power up via the pin header? I've bumped into the same issue.

**Comment by kgh-85** [comment]
@hjonnala @tsuijten @yaroslavdu 
For your info: I shortened the PowerButton and the board now boots up automatically, using the Power USB-C connector (same behavier as the OTG port now) OR via GPIOs - both works and doesn't turns the board off after 20 seconds. Running stable now for hours. Maybe there was a recent firmware update that introduced that change? I'm on version 5.3

Pic attached for other folks (connect the two pads of the power button on the left):
![image](https://github.com/google-coral/edgetpu/assets/59069726/a6b76afb-a8e2-411f-a0c4-783009478a24)
