### ISSUE TITLE
Building tflite_runtime python wheel using pip_package of the release 2.2

### ISSUE THREAD

**Issue by othmaneAZ** [google-coral/edgetpu#71]
I succeeded to build my own pip package using using this commit tensorflow/tensorflow@d855adf and it worked fine for me. I can run an inference on the Edge TPU without any error and by using `tflite.load_delegate` and I can see that this commit was pulled from the master branch. I tried to build the python wheel using the pip_package of the that release (2.2) but I'm getting this error: 

`RuntimeError: Internal: :159 batches * single_input_size != input->bytes (150528 != 12544)Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare. `

Do you have any idea what are the important patches that I'll be needing if I want to build a reliable working python wheel (Giving similar results to this commit tensorflow/tensorflow@d855adf ) and base my commit on the last release r2.2.

**Comment by Namburger** [comment]
@othmaneAZ unfortunately, there are some changes in the tensorflow commits after https://github.com/tensorflow/tensorflow/commit/d855adf that breaks our api. I understand that there are new features beyond that form the tensorflow team, but currently that isn't compatible with our runtime library, but we are working on this.

**Comment by othmaneAZ** [comment]
@Namburger Thank you for your answer. But what I am actually asking for is the previous and decisive commits that have been useful to make this tensorflow/tensorflow@d855adf reliable. I'm looking to extract the patches so I can apply them on the r2.2 to get a working wheel using pip_package.

**Comment by Namburger** [comment]
@othmaneAZ I'm trying to confirm this right now and will give you update hopefully soon. But as far as I know, it's not a patch in https://github.com/tensorflow/tensorflow/commit/d855adf that make it works, but the new features beyond that commit that is breaking our runtime. I'll update you on this

**Comment by Namburger** [comment]
@othmaneAZ 
Just confirmed, since libedgetpu.so AKA `libedgetpu1-std:* 13.0` is linked against that specific commit of tensorflow when we built it, it just won't be compatible.
On the next release, we'll build the new libedgetpu along with the most recent tensorflow commit so that's what we'll have to wait for.

**Comment by othmaneAZ** [comment]
@Namburger thank you for your concern. I understand that there were some new features that broke the runtime. I ll be waiting for this next release. 
In the meantime, I have another question, I'm trying now to base my python wheel on an official release (r2.1 this time). Same question, what are the important commits that made tensorflow/tensorflow@d855adf reliable, knowing that it was based on the master branch. In other words, what patches will I be needing to make a reliable working wheel on the r2.1 using the pip_package tool ?

**Comment by othmaneAZ** [comment]
@Namburger any hints to base it on the r2.1 tensorflow release ?

**Comment by Namburger** [comment]
@othmaneAZ 
Ahh sorry, I missed the latest response from you. But what I'm trying to say is that there is no patch in https://github.com/tensorflow/tensorflow/commit/d855adf that makes it compatible with our runtime, it's just the fact that it was built together. So in order to use newer version of tensorflow, we'll have to wait until newer release of our runtime too, unfortunately. Apologies for this, I know it's not the best workflow.

**Comment by othmaneAZ** [comment]
@Namburger Thank you so much for your concern and your answer. I'll have to wait for the next release and hopefully it will be compatible with the Edge TPU runtime. I'm seeking for some interesting features, If I'm finding anything new I'll let you know. 
Though, I have another question, do you have any idea if can I get the source code of the libedgetpu.so, I'm trying to compile it during a bitbake (I'm using OpenEmbedded to make a distribution) ?

**Comment by Namburger** [comment]
@othmaneAZ So the main issue is actually because `libedgetpu` is not open source, unfortunately :(

If it was opensource, you can build it while having it linked with any tensorflow version you want which makes this process a lot easier. But since it's not, we do have to release both the runtime and the tflite wheel package. I believe we do have plan to make this happen in the future, but I can't review much details either.
