### ISSUE TITLE
Regarding Boot2Qt

### ISSUE THREAD

**Issue by Sureshee** [google-coral/edgetpu#9]
Has anyone tried to use Qt framework in edge dev board ? Is it possible to boot using Its bopt2qt device creation framework? I tried to find suitable document for using it with uboot but I cannot find any useful resources online.

**Comment by Namburger** [comment]
@Sureshee I'm not super familiar with boot2qt (I've only used QT Creator before), so don't quote me on this one. However, I think you should be able to build an image that is suited for the NXP i.MX8 (dev board CPU) as listed in the link below and dd it to a microSD, which you can in turn boot into that instead of the eMMC:
https://doc.qt.io/QtForDeviceCreation/qtdc-supported-platforms.html#embedded-reference-target-devices

Although I'm not sure if it's a good idea since this image won't have the drivers necessary to interact with the EdgeTPU

**Comment by mtyka** [comment]
I don't know Boot2Qt but in generall, yes you can use Qt on the devboard. Here's an example:

Simple "hello world" app:
```
#include <QApplication>
#include <QPushButton>
int main(int argc, char **argv) {
 QApplication app (argc, argv);
 QPushButton button ("Hello world !");
 button.show();
 return app.exec();
}
```

```CMakeLists.txt``` for building:

```
cmake_minimum_required(VERSION 3.1.0)
project(helloworld)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)
if(CMAKE_VERSION VERSION_LESS "3.7.0")
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()
find_package(Qt5 COMPONENTS Widgets REQUIRED)
add_executable(helloworld main.cc )
target_link_libraries(helloworld Qt5::Widgets)
```


To run do:
```
sudo apt install qtbase5-dev qtwayland5 
cmake ./
make
./hello_world -platform wayland
```
