### ISSUE TITLE
Compiler failing with big input tensors

### ISSUE THREAD

**Issue by VitaliKaiser** [google-coral/edgetpu#95]
Hi, 

I wanted to measure the execution time for different input resolutions but it seems at a certain point the compiler cant handle them any more. I did a similar test with the old compiler which did crash. Now its not crashing but taking forever. I tried FullHD compiling for 12 hours and it was still not finished.
I noticed that my memory was almost totally allocated during this.
Is this due what the compiler needs to do (and there is no other way for big resolutions), or could this be fixed (add e.g. a parameter of max memory)?

BTW: Will it be someday possible to use the `tf.lite.Interpreter.resize_tensor_input` method with the coral stick (for e.g. FCNs) or is this not possible because of how the system is designed?

OT: I wonder how much memory is needed during inference. Just the input and output, or also some additionally memory to store intermediate results?

```
edgetpu_compiler --version
Edge TPU Compiler version 2.1.302470888
```

I attached my tflite model, and here you find the total code of the experiment:
[model_int8_1920x1080.zip](https://github.com/google-coral/edgetpu/files/4492824/model_int8_1920x1080.zip)

```
import os
import pathlib

import tensorflow as tf
import cv2
import numpy as np

num_calibration_steps = 10
shape = (1920, 1080, 3)

tflite_models_dir = pathlib.Path("tflite_models")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

inputs = tf.keras.Input(shape=shape)
mobilenet = tf.keras.applications.mobilenet_v2.MobileNetV2(input_shape=shape, alpha=1.0, include_top=False, weights='imagenet', input_tensor=None, pooling=None)

def representative_dataset_gen():
   # I use some random images here


# do it with v1 compat
mobilenet.save('model.h5')
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file('model.h5')
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# switch dtype to signed int
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

tflite_model_quant_file = tflite_models_dir/f"model_int8_{shape[0]}x{shape[1]}.tflite"
open(tflite_model_quant_file, 'wb').write(tflite_model)
```

Best,
Vitali

**Comment by Namburger** [comment]
@VitaliKaiser The inputs of this model is just too big to fits in the tpu's chip, unfortunately. I suggest shrinking the input tensors and try again. 
The compiler hanging without crashes is definitely a bug but my compiler from source tells me more details. This fix will be out in a future release!
As far as `tf.lite.Interpreter.resize_tensor_input`, I'll have to get back with you on this since it's a little more specific. The current workflow is to just preprocess the image to fits the model's input tensor before feeding it to the interpreter like [this](https://github.com/google-coral/tflite/blob/master/python/examples/detection/detect_image.py#L99) for example.
Apologies for the limitations, I know what if the model is way too big, you can always try our new [model pipelining](https://coral.ai/docs/edgetpu/pipeline/) feature. But if the input tensors are too big, we don't have a solution at the moment :/

**Comment by VitaliKaiser** [comment]
Thanks for the feedback! Unfortunately, for my usecase I would need a FullHD resolution. But anyways, thanks for the update and fixing the errors.

**Comment by Namburger** [comment]
apologies, I'll give you an update resize_tensor_input.
