### ISSUE TITLE
EdgeTPU models don't work with minimal application

### ISSUE THREAD

**Issue by jlz3008** [google-coral/edgetpu#98]
I made a Pull request to compile **minimal** example in Dev Board https://github.com/google-coral/edgetpu/pull/97#issue-405651070

But I can't execute it successfully with  **edgetpu** models.

```
mendel@undefined-dog:~/coral/edgetpu/src/cpp/examples$  LD_LIBRARY_PATH=/home/mendel/coral/edgetpu/libedgetpu/direct/aarch64 ./minimal ~/coral/edgetpu/test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite ~/coral/edgetpu/test_data/resized_cat.bmp 
ERROR: Internal: Unsupported data type in custom op handler: -610837120
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

Failed to allocate tensors.
Segmentation fault
```

But works with tflite models

```
LD_LIBRARY_PATH=/home/mendel/coral/edgetpu/libedgetpu/direct/aarch64 ./minimal
 ~/coral/edgetpu/test_data/mobilenet_v1_1.0_224_quant.tflite ~/coral/edgetpu/test_data/resized_cat.bmp
[Image analysis] max value index: 286 value: 0.804688
```

The models works with python demos

```
mendel@undefined-dog:~/coral/tflite/python/examples/classification$ LD_LIBRARY_PATH=/home/mendel/coral/edgetpu/libedgetpu/direct/aarch64 python3 classify_image.py --model ~/coral/edgetpu/test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite --input  ~/coral/edgetpu/test_data/resized_cat.bmp 
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
14.6ms
2.3ms
2.3ms
2.3ms
2.3ms
-------RESULTS--------
286: 0.79297
```

**Comment by Namburger** [comment]
@jlz3008 Really appreciate the PR and the attention for this repo!!
Unfortunately, our repo right now has some blocking issues to take in PRs due to how it's structured internally. We are working diligently to come up with a solution for PRs which I expected to be working in the future. 
On another note, your build seems to be segfault-ing on the dev board, which isn't something we'd need to add. I recently worked on a native build solution to allow this example to be build natively. Please checkout this minimal repo:
https://github.com/Namburger/edgetpu-minimal-example
Let me know if you have issues using it!

**Comment by jlz3008** [comment]
Thanks for your code @Namburger . It works. 
I can see that the minimal.cc and model_utils.cc code is almost identical to google-coral/edgetpu repo so I guess the difference is in the tflite and other dependences repos.
I need some time to understand how to the build works in your repo code.

Thanks.

**Comment by Namburger** [comment]
@jlz3008 no worries, please ask if you have any questions!
